[platformio]
default_envs = native

[env]
test_framework = unity

[env:native]
platform = native
test_build_src = no
build_src_filter = -<*>
build_flags =
    -std=gnu++17
    -Iinclude

[env:native_tx_gate]
extends = env:native
build_flags =
    -std=gnu++17
    -Iinclude
    -DBLDC_ENABLE_CAN_TRANSMIT=1
[env:nucleo_f103rb]
platform = ststm32
board = nucleo_f103rb
framework = stm32cube
build_src_filter =
    +<*>
    -<tx_tutorial_main.cpp>
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -fno-exceptions
    -DBLDC_ENABLE_CAN_TRANSMIT=0

[env:nucleo_f103rb_tx_review]
extends = env:nucleo_f103rb
build_unflags =
    -std=gnu++11
    -DBLDC_ENABLE_CAN_TRANSMIT=0
build_flags =
    -std=gnu++17
    -fno-exceptions
    -DBLDC_ENABLE_CAN_TRANSMIT=1

[env:nucleo_f103rb_tx_tutorial]
extends = env:nucleo_f103rb
build_src_filter =
    +<*>
    -<main.cpp>
build_unflags =
    -std=gnu++11
    -DBLDC_ENABLE_CAN_TRANSMIT=0
build_flags =
    -std=gnu++17
    -fno-exceptions
    -DBLDC_ENABLE_CAN_TRANSMIT=1
